language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew clean test

branches:
  except:
    - gh-pages

notifications:
  email: true

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
